### ISSUE TITLE
Errors while setting up the project

### ISSUE THREAD

**Issue by developertj** [shashiben/Hostel-Management#4]
I am getting many errors while installing npm in the frontend. I have attached the photo for your reference. Please help me.
![image](https://github.com/shashiben/Hostel-Management/assets/97594856/4fbc8c04-67a0-48c5-9ea8-8653921697d1)
![image](https://github.com/shashiben/Hostel-Management/assets/97594856/ca51025f-da82-4b99-9c27-bd7df7ece1a9)

**Comment by shashiben** [comment]
did u tried npm install --force

**Comment by shashiben** [comment]
Closing this as there is no any update
